[package]
name = "starki_contract"
version = "0.0.1"
edition = "2023_10"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.8.0" }
starknet = "2.3.1"

[[target.starknet-contract]]
# Enable Sierra codegen.
sierra = true

Starki = { path = "src/starki" }

# Enable CASM codegen.
casm = true


[tool.sncast]
account = "your_name"
accounts-file = "your_account_file.json"
url = "your_rpc_endpoint"